// backend/middleware/roles.js
// Definición centralizada de roles. Siempre MAYÚSCULAS.

const ROLES = {
  ADMIN: "ADMIN",
  ADMINISTRACION: "ADMINISTRACION",
  ENCARGADO_GENERAL: "ENCARGADO_GENERAL",
  INSPECTOR: "INSPECTOR",
  JEFE_BARRIO: "JEFE_BARRIO",
  PERMISIONARIO: "PERMISIONARIO",
  POSTULANTE: "POSTULANTE",
};

module.exports = ROLES;
