const ALOJAMIENTO_DOCUMENTO_CODIGOS = Object.freeze([
  "ANEXO_21",
  "ANEXO_22",
  "ANEXO_23",
  "ANEXO_24",
  "ANEXO_25",
  "ANEXO_26",
  "ANEXO_28",
]);

const ALOJAMIENTO_DOCUMENTO_ESTADOS = Object.freeze([
  "BORRADOR",
  "ENVIADO",
  "EN_REVISION",
  "CERRADO",
  "RECHAZADO",
  "ANULADO",
]);

const ALOJAMIENTO_DOCUMENTO_ROLES = Object.freeze([
  "POSTULANTE",
  "ADMIN_GENERAL",
  "ADMIN",
  "INSPECTOR",
  "ALOJADO",
]);

const ALOJAMIENTO_DOCUMENTO_TRANSICIONES = Object.freeze({
  BORRADOR: Object.freeze(["ENVIADO", "ANULADO"]),
  ENVIADO: Object.freeze(["EN_REVISION", "RECHAZADO", "ANULADO"]),
  EN_REVISION: Object.freeze(["CERRADO", "RECHAZADO", "ANULADO"]),
  CERRADO: Object.freeze([]),
  RECHAZADO: Object.freeze([]),
  ANULADO: Object.freeze([]),
});

const ALOJAMIENTO_DOCUMENTOS_MULTIPLES_POR_ORIGEN = Object.freeze([
  "ANEXO_24",
  "ANEXO_28",
]);

const ALOJAMIENTO_DOCUMENTOS_UNICOS_POR_ORIGEN = Object.freeze(
  ALOJAMIENTO_DOCUMENTO_CODIGOS.filter(
    (codigo) => !ALOJAMIENTO_DOCUMENTOS_MULTIPLES_POR_ORIGEN.includes(codigo)
  )
);

module.exports = {
  ALOJAMIENTO_DOCUMENTO_CODIGOS,
  ALOJAMIENTO_DOCUMENTO_ESTADOS,
  ALOJAMIENTO_DOCUMENTO_ROLES,
  ALOJAMIENTO_DOCUMENTO_TRANSICIONES,
  ALOJAMIENTO_DOCUMENTOS_MULTIPLES_POR_ORIGEN,
  ALOJAMIENTO_DOCUMENTOS_UNICOS_POR_ORIGEN,
};
